# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szklarnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('reservations', models.CharField(max_length=70)),
                ('img_url', models.CharField(max_length=70)),
            ],
        ),
    ]
